  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/learnjwt
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true

  application:
    security:
      jwt:
        secret-key: 6250655368566B5970337336763979244226452948404D635166546A576E5A71
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 days
  redis:
    host: localhost
    port: 6379
#  security:
#    security:
#      oauth2:
#        client:
#          registration:
#            github:
#              clientId: Iv1.731596c579d3b990
#              clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d
#            google:
#              clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
#              clientSecret: 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
